eureka:
  hostname: localhost:8080
  instance:
    metadata-map:
#      设置集群名称
      cluster: turbine
      key: val
    lease-renewal-interval-in-seconds: 10
  #      实例ID 默认spring.application.name
#    instance-id: eureka-client-id1
  #    eureka server访问url
#    status-page-url: https://${eureka.hostname}/info
#    health-check-url: https://${eureka.hostname}/health
#    home-page-url: https://${eureka.hostname}/
  #    HTTPS
#    non-secure-port-enabled: false
#    secure-port-enabled: true
#    status-page-url: /custom/info
#    health-check-url-path: /custom/health
  client:
    refresh:
      enable: true
    healthcheck:
      enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client1
#暴露端点，Hystrix Dashboard 才能访问http://localhost:8080/actuator/hystrix.stream
#http://localhost:8080/turbine.stream
#http://localhost:8080/turbine.stream?cluster=turbine
management:
  endpoints:
    web:
      exposure:
        include: '*'
turbine:
  combine-host-port: true
  aggregator:
    cluster-config: turbine
  cluster-name-expression: metadata['cluster']
  app-config: eureka-client1

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000

    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
user:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

#在Ribbon禁用Eureka
ribbon:
  eureka:
    enabled: false