eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: feign-provider
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: '*'
